#ifndef FSVULKANDEF_IS_INCLUDED
#define FSVULKANDEF_IS_INCLUDED
/* { */

#define YSVULKAN_TEX_TYPE_NONE                0
#define YSVULKAN_TEX_TYPE_TILING              1
#define YSVULKAN_TEX_TYPE_BILLBOARD           2
#define YSVULKAN_TEX_TYPE_3DTILING            3
#define YSVULKAN_TEX_TYPE_ATTRIBUTE           4
#define YSVULKAN_TEX_BILLBOARD_PERS           0
#define YSVULKAN_TEX_BILLBOARD_ORTHO          1
#define YSVULKAN_TEX_WRAP_CUTOFF              0
#define YSVULKAN_TEX_WRAP_REPEAT              1
#define YSVULKAN_POINTSPRITE_CLIPPING_NONE    0
#define YSVULKAN_POINTSPRITE_CLIPPING_CIRCLE  1
#define YSVULKAN_MARKER_TYPE_PLAIN            0
#define YSVULKAN_MARKER_TYPE_CIRCLE           1
#define YSVULKAN_MARKER_TYPE_RECT             2
#define YSVULKAN_MARKER_TYPE_STAR             3
#define YSVULKAN_MARKER_TYPE_EMPTY_RECT       4
#define YSVULKAN_MARKER_TYPE_EMPTY_CIRCLE     5
#define YSVULKAN_MARKER_TYPE_EMPTY_STAR       6
#define YSVULKAN_MAX_NUM_LIGHT                4
#define YSVULKAN_POINTSPRITE_SIZE_IN_PIXEL    0
#define YSVULKAN_POINTSPRITE_SIZE_IN_3DSPACE  1
#define YSVULKAN_RENDERER_TYPE_NONE           0
#define YSVULKAN_RENDERER_TYPE_PLAIN2D        1
#define YSVULKAN_RENDERER_TYPE_MARKER2D       2
#define YSVULKAN_RENDERER_TYPE_POINTSPRITE2D  3
#define YSVULKAN_RENDERER_TYPE_PLAIN3D        10
#define YSVULKAN_RENDERER_TYPE_SHADED3D       11
#define YSVULKAN_RENDERER_TYPE_FLASH          12
#define YSVULKAN_RENDERER_TYPE_MARKER3D       13
#define YSVULKAN_RENDERER_TYPE_POINTSPRITE3D  14
#define YSVULKAN_SHADOWMAP_MAX_NUM_TEXTURE    4
#define YSVULKAN_SHADOWMAP_NONE               0
#define YSVULKAN_SHADOWMAP_USE                1
#define YSVULKAN_SHADOWMAP_DEBUG              2

/* } */
#endif
